### ISSUE TITLE
ImportError: No module named '{{ project_name }}'

### ISSUE THREAD

**Issue by tbell511** [pinax/pinax-projects#48]
I downloaded the account starter project, however I can not get past this error.  Has anybody seen this error before?  

```
(pinaxstarter) Tylers-MacBook-Pro:pinax-starter-projects-account Tyler$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Tyler/Desktop/pinax-starter-projects-account/pinaxstarter/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/Tyler/Desktop/pinax-starter-projects-account/pinaxstarter/lib/python3.4/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/Users/Tyler/Desktop/pinax-starter-projects-account/pinaxstarter/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/Tyler/Desktop/pinax-starter-projects-account/pinaxstarter/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/Tyler/Desktop/pinax-starter-projects-account/pinaxstarter/lib/python3.4/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/Tyler/Desktop/pinax-starter-projects-account/pinaxstarter/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named '{{ project_name }}'
```

**Comment by half0wl** [comment]
@formatically The starter projects here are `django-admin startproject` templates, so you have to install Django first and pass the starter project as a template.

```
$ pip install django
$ django-admin startproject \
    --template=https://github.com/pinax/pinax-starter-projects/zipball/account \
    <your_project_name>
```

**Comment by jtauber** [comment]
or use `pinax-cli` which makes this easier
